### ISSUE TITLE
bottle startproject MyProject  has error

### ISSUE THREAD

**Issue by idevsoft** [avelino/bottle-boilerplate#2]
Python 2.7.9, run 'bottle startproject MyProject'  has error message :
pkg_resources.VersionConflict: click 4.0 is installed but click<4.0 is required by ['cookiecutter']

Requirement should be updated.

**Comment by erichideki** [comment]
I have the same issue.

**Comment by erichideki** [comment]
I found the error. My mistake. 

The problem is not the bottle-boilerplate, is the Cookiecutter that not update the version stable of the Click package. I will open an issue of that in Cookiecutter repository.

Until now, the bottle-boilerplate need to be use click==3.3

**Comment by avelino** [comment]
Fixed in PR #4 by @erichideki
